// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PoorMansTSqlFormatterSSMSPackage
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPoorMansTSqlFormatterSSMSVSPackagePkgString = "247609b1-2692-47d6-972a-976544685f0e";
        public static Guid guidPoorMansTSqlFormatterSSMSVSPackagePkg = new Guid(guidPoorMansTSqlFormatterSSMSVSPackagePkgString);

        public const string guidPoorMansTSqlFormatterSSMSVSPackageCmdSetString = "5ea2e413-8351-4ca9-b0a0-34a9b241648b";
        public static Guid guidPoorMansTSqlFormatterSSMSVSPackageCmdSet = new Guid(guidPoorMansTSqlFormatterSSMSVSPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidPoorMansFormatSQL = 0x0100;
        public const int cmdidPoorMansSqlOptions = 0x0101;
    }
}
